#ifndef APPLLED_CFG_H_
#define APPLLED_CFG_H_

#include <psply/ApplPsply_CFG.h>
#include <rte/Rte_ApplLed.h>

#define APPLLED_PSPLY_INIT (APPLPSPLY_PSPLY_INIT)
#define APPLLED_PSPLY_NONOP (APPLPSPLY_PSPLY_NONOP)
#define APPLLED_PSPLY_OP (APPLPSPLY_PSPLY_OP)
#define APPLLED_PSPLY_ACTIVE_OFF (APPLPSPLYL_PSPLY_ACTIVE_OFF)
#define APPLLED_PSPLY_ACTIVE_ON (APPLPSPLY_PSPLY_ACTIVE_ON)

#endif /* APPLLED_CFG_H_ */
