#ifndef SYSTEM_MACRO_H
#define SYSTEM_MACRO_H

#define TRUE 1
#define FALSE 0

#define USE_SEMIHOSTING_ENABLED			FALSE
#define NOT_PRESSED 					FALSE
#define PRESSED 						TRUE
#define DC_MOTOR_USED					FALSE
#define ULTRASONIC_WAVE_SENSOR_USED		FALSE
#define USART_USED						TRUE
#define MPU6050_USED					TRUE
#define PUSH_BUTTON_PE0_USED			TRUE
#define CAN_TX_USED						FALSE
#define CAN_RX_USED						TRUE
#define CAN_ANALYZER_MODE				TRUE

#endif
